CREATE DATABASE IF NOT EXISTS sistema_reservas;
USE sistema_reservas;

CREATE TABLE IF NOT EXISTS USUARIOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS TIPO_ESPACOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) UNIQUE NOT NULL 
);

INSERT IGNORE INTO TIPO_ESPACOS (id, nome) VALUES (1, 'Sala de Reunião'), (2, 'Auditório'), (3, 'Laboratório');

CREATE TABLE IF NOT EXISTS ESPACOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    capacidade INT NOT NULL,
    descricao TEXT,
    tipo_espaco_id INT,
    FOREIGN KEY (tipo_espaco_id) REFERENCES TIPO_ESPACOS(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT NOT NULL,
    espaco_id INT NOT NULL,
    data DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    status ENUM('PENDENTE', 'CONFIRMADA', 'CANCELADA') DEFAULT 'PENDENTE',
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    FOREIGN KEY (espaco_id) REFERENCES ESPACOS(id) ON DELETE RESTRICT
);